apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: velero-allow-only-necessary
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "velero.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
        - podSelector: {} # Adjust to only allow specific trusted pods if needed
      ports:
        - protocol: TCP
          port: 443
  egress:
    - to:
        - podSelector: {} # Adjust to only allow required destinations
      ports:
        - protocol: TCP
          port: 443
