apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: velero-allow-k8s-api
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "velero.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
          # Optionally restrict this further by podSelector or IPBlock
  egress:
    - to:
        - namespaceSelector: {}
  # Optionally define ports
